# Bourne-Again SHell, a UNIX command interpreter
brew "bash"
# Clone of cat(1) with syntax highlighting and Git integration
brew "bat"
# Cross-platform make
brew "cmake"
# Command-line fuzzy finder written in Go
brew "fzf"
# GNU debugger
brew "gdb"
# C++ microbenchmark support library
brew "google-benchmark"
# Google Testing and Mocking Framework
brew "googletest"
# Improved top (interactive process viewer)
brew "htop"
# Ambitious Vim-fork focused on extensibility and agility
brew "neovim"
# Open-source, cross-platform JavaScript runtime environment
brew "node"
# Execute binaries from Python packages in isolated environments
brew "pipx"
# Search tool like grep and The Silver Searcher
brew "ripgrep"
# Terminal multiplexer
brew "tmux"
# Display directories as trees (with optional color/HTML output)
brew "tree"
# Menu bar manager
cask "jordanbaird-ice"
# Mesh VPN based on WireGuard
cask "tailscale-app"
vscode "anysphere.cursorpyright"
vscode "anysphere.remote-ssh"
vscode "matepek.vscode-catch2-test-adapter"
vscode "ms-python.debugpy"
vscode "ms-python.python"
vscode "ms-vscode.cmake-tools"
vscode "ms-vscode.cpptools"
vscode "ms-vscode.cpptools-extension-pack"
vscode "ms-vscode.cpptools-themes"
vscode "twxs.cmake"
